# spring:
#   autoconfigure:
#     exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration

# mybatis:
#   typeAliasesPackage: com.dotk.**.infra.mapper
#   mapper-locations:
#   - classpath*:mapper/**/*Mapper.xml
#   - classpath*:mapper/*Mapper.xml

# # 用户配置
# user:
#   password:
#     # 密码最大错误次数
#     maxRetryCount: 5
#     # 密码锁定时间（默认10分钟）
#     lockTime: 10

# # token配置
# token:
#     # 令牌自定义标识
#     header: Auth-Token
#     # 令牌密钥
#     secret: abcdefghijklmnopqrstuvwxyz111122222222abcdefghijklmnopqrstuvwxyz111122222222
#     # 令牌有效期（默认30分钟）
#     expireTime: 30

# 日志
logging:
  level:
    # 打印 mybatis日志
    com.dotk.oauth.infra.mapper : debug